environment:
  sdk: ">=3.0.0 <4.0.0"     # Dart 3
  flutter: ">=3.7.0"        # Flutter 3+

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  file_picker: ^8.0.3
  http: ^1.2.1
  path: ^1.9.0
  pointer_interceptor: ^0.10.1
  uuid: ^4.3.3

  # Família WebView (alinhar as majors)
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
webview_flutter_wkwebview: ^3.10.2
  webview_flutter_platform_interface: ^2.13.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/quill_html_editor_v2/assets/camera_roll_icon.png
    - packages/quill_html_editor_v2/assets/h1_dark.png
    - packages/quill_html_editor_v2/assets/h2_dark.png
    - packages/quill_html_editor_v2/assets/edit_table.png
    - packages/quill_html_editor_v2/assets/insert_table.png
    - packages/quill_html_editor_v2/assets/delete_column.png
    - packages/quill_html_editor_v2/assets/delete_row.png
    - packages/quill_html_editor_v2/assets/delete_table.png
    - packages/quill_html_editor_v2/assets/insert_column_left.png
    - packages/quill_html_editor_v2/assets/insert_row_above.png
    - packages/quill_html_editor_v2/assets/insert_row_below.png
    - packages/quill_html_editor_v2/assets/insert_column_right.png
    - packages/quill_html_editor_v2/assets/scripts/quill_2.0.0_4_min.js
